name: Build and Release Zygisk Module

on:
  push:
    tags:
      - 'v*'  # Chạy workflow khi có tag bắt đầu bằng "v"
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  build:
    name: Build Zygisk Module
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Android SDK and NDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          ndk: true
          ndk-version: '25.2.9519653'

      # 3. Build module
      - name: Build Zygisk Module
        run: |
          mkdir -p build
          cd zygisk
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-21 \
                -DCMAKE_BUILD_TYPE=Release \
                -B../build
          cmake --build ../build || exit 1

      # 4. Debug build output
      - name: Debug Build Output
        run: |
          ls -R build

      # 5. Package Zygisk Module
      - name: Package Zygisk Module
        run: |
          mkdir -p output
          cp -r module.prop post-fs-data.sh service.sh config output/
          cp build/libzygisk.so output/zygisk/zygisk.so
          cd output
          zip -r ../Zygisk-prop-app.zip ./*

      # 6. Upload release to GitHub
      - name: Upload to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: Zygisk-prop-app.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Zygisk Prop App v${{ github.ref_name }}
          body: |
            # Zygisk Prop App Module
            Automatically generated release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false
